### ISSUE TITLE
CSRFの対策

### ISSUE THREAD

**Issue by saya-minm** [saya-minm/lamp_practice#10]
トークンの生成
- [x] functions.php

formに埋め込み
- [x] admin_view.php
- [x] cart_view.php
- [x] index_view.php
- [x] login_view.php
- [x] signup_view.php

トークンのチェック
- [x] admin_insert.php
- [x] admin_change_status.php
- [x] cart_delete_cart.php
- [x] finish.php
- [x] cart_change_amount.php
- [x] index_add_cart.php
- [x] login_process.php
- [x] signup_process.php

**Comment by hisys** [comment]
X-Frame-Options対策は大丈夫ですか。
[このページ](https://qiita.com/kan-no/items/d1621a06a01086044835)などもご参考に。

**Comment by saya-minm** [comment]
ありがとうございます！すみません、いくつか質問があるのですが、
  header('X-FRAME-OPTIONS: DENY');
だと、全てのviewのページに入れないといけないのでしょうか？
また、Header set X-FRAME-OPTIONS "DENY"
だと、.htaccessファイルを作成し、そのまま記述しても大丈夫でしょうか？

**Comment by hisys** [comment]
.htaccessファイルは、Webサーバーが参照するファイルです。
今回の課題は、PHPスクリプトを使用しましょう。
header('X-FRAME-OPTIONS: DENY');を
->全てのviewのページに入れないといけないのでしょうか？
はい、そのようになりますね。

**Comment by saya-minm** [comment]
わかりました！ありがとうございます！
