### ISSUE TITLE
クロスサイトスクリプティングの対策

### ISSUE THREAD

**Issue by saya-minm** [saya-minm/lamp_practice#6]
print時にh関数をついかする

- [x] admin_view
- [x] cart_view
- [x] finish_view
- [x] index_view
- [x] login_view
- [x] signup_view
- [x] header_logined
- [x] header
- [x] messages

**Comment by thisprodigiousgeek** [comment]
はい、こちらの方針でバッチリです！
Issueブランチを作成して実装しましょう！
